export function getMarketingCampaigns() {
  return [
    {
      id: 1,
      name: 'Summer Health Boost',
      type: 'Email',
      status: 'Active',
      startDate: new Date(2023, 5, 1),
      endDate: new Date(2023, 7, 31),
      budget: 5000,
      spent: 3250,
      leads: 1875,
      conversions: 342,
    },
    {
      id: 2,
      name: 'Fall Immunity Bundle',
      type: 'Social Media',
      status: 'Scheduled',
      startDate: new Date(2023, 8, 15),
      endDate: new Date(2023, 10, 15),
      budget: 7500,
      spent: 0,
      leads: 0,
      conversions: 0,
    },
    {
      id: 3,
      name: 'New Customer Discount',
      type: 'Google Ads',
      status: 'Active',
      startDate: new Date(2023, 0, 1),
      endDate: new Date(2023, 11, 31),
      budget: 12000,
      spent: 8750,
      leads: 4250,
      conversions: 830,
    },
    {
      id: 4,
      name: 'Referral Program',
      type: 'Referral',
      status: 'Active',
      startDate: new Date(2023, 2, 1),
      endDate: null,
      budget: 3000,
      spent: 2100,
      leads: 1350,
      conversions: 520,
    },
    {
      id: 5,
      name: 'Back to School Wellness',
      type: 'Email',
      status: 'Completed',
      startDate: new Date(2023, 7, 1),
      endDate: new Date(2023, 8, 15),
      budget: 4500,
      spent: 4500,
      leads: 2200,
      conversions: 385,
    },
  ];
}
